export default {
   gray: 'gray',
   black: 'black',
   dark: 'black',
   label: '#f1f1f1',
   primary: '#1C6DD0',
   secondary: 'lightgray',
   success: 'gren',
   warning: 'yellow',
   danger: 'red',
   light: '#f1f1f1',
   white: 'white',
   default: 'lightgray',
   info: 'skyblue',
   pageBg: 'white',
   textColor: '#191919',
}
